### ISSUE TITLE
Cannot start custom integration "elro_connects" after 2023.08.03

### ISSUE THREAD

**Issue by jodewee** [jbouwh/ha-elro-connects#42]
This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/elro_connects/device.py:10
Integration: Elro Connects (documentation, issues)
First occurred: 09:29:49 (1 occurrences)
Last logged: 09:29:49

Setup failed for custom integration elro_connects: Unable to import component: cannot import name 'K1' from 'elro.api' (/usr/local/lib/python3.11/site-packages/elro/api.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/elro_connects/__init__.py", line 12, in <module>
    from .device import ElroConnectsK1
  File "/config/custom_components/elro_connects/device.py", line 10, in <module>
    from elro.api import K1
ImportError: cannot import name 'K1' from 'elro.api' (/usr/local/lib/python3.11/site-packages/elro/api.py)

**Comment by jodewee** [comment]
already tried to re-install, but nothing seems te work.
For now, reverting to HA core 2023.08.02

**Comment by jbouwh** [comment]
It runs fine here with 2023.8.3. Not sure why the import fails. 
Did you use HACS to install?

**Comment by jodewee** [comment]
Yes, it's imported via hacs

**Comment by jbouwh** [comment]
I'll try to reinstall it myself. May be done dependencies need an update.

**Comment by jodewee** [comment]
ok, thanks in advance!

**Comment by jodewee** [comment]
it works again when i reverted to 2023.08.02. 
did again the update to 2023.08.03 --> OK now. probably something went wrong on the update process.
You may close this one
